name: crypto_hmac
description: HMAC SHA256 - AES based encrypt/decrypt .
version: 1.0.0
homepage: https://github.com/karacaemre/crypto_hmac
repository: https://github.com/karacaemre/crypto_hmac
issue_tracker: https://github.com/karacaemre/crypto_hmac/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  convert: ^3.1.1
  tuple: ^2.0.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  flutter_lints: ^3.0.0
